spring.application.name=tubenotify-backend
spring.output.ansi.enabled=ALWAYS

# DATABASE PostgresSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/tubenotifydb
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_USERNAME}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=create
spring.jpa.hibernate.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
# spring.jpa.properties.hibernate.format_sql=true
